package Entities;
// Generated Jan 13, 2018 5:54:31 PM by Hibernate Tools 5.1.0.Alpha1

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DobavljacKupacSirovina generated by hbm2java
 */
@Entity
@Table(name = "dobavljac_kupac_sirovina", catalog = "fabrika_sladoleda")
public class DobavljacKupacSirovina implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int id;
	private DobavljacKupac dobavljacKupac;
	private Sirovina sirovina;
	private Date datumPristeca;

	public DobavljacKupacSirovina() {
	}

	public DobavljacKupacSirovina(int id, DobavljacKupac dobavljacKupac, Sirovina sirovina) {
		this.id = id;
		this.dobavljacKupac = dobavljacKupac;
		this.sirovina = sirovina;
	}
	
	public DobavljacKupacSirovina(DobavljacKupac dobavljacKupac, Sirovina sirovina) {
		this.dobavljacKupac = dobavljacKupac;
		this.sirovina = sirovina;
	}
	
	
	

	public DobavljacKupacSirovina(DobavljacKupac dobavljacKupac, Sirovina sirovina, Date datumPristeca) {
		this.dobavljacKupac = dobavljacKupac;
		this.sirovina = sirovina;
		this.datumPristeca = datumPristeca;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DOBAVLJACID", nullable = false)
	public DobavljacKupac getDobavljacKupac() {
		return this.dobavljacKupac;
	}

	public void setDobavljacKupac(DobavljacKupac dobavljacKupac) {
		this.dobavljacKupac = dobavljacKupac;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SIROVINAID", nullable = false)
	public Sirovina getSirovina() {
		return this.sirovina;
	}

	public void setSirovina(Sirovina sirovina) {
		this.sirovina = sirovina;
	}
	
	
	@Column(name = "DATUM_PRISTECA", nullable = false, length = 0)
	public Date getDatumPristeca() {
		return datumPristeca;
	}

	public void setDatumPristeca(Date datumPristeca) {
		this.datumPristeca = datumPristeca;
	}

	@Override
	public String toString() {
		return "DobavljacKupacSirovina [dobavljacKupac=" + dobavljacKupac + ", sirovina=" + sirovina
				+ ", datumPristeca=" + datumPristeca + "]";
	}

	
}
